// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhc8oPyotczsRX_YQwJjgh0QnXMJDvykE',
    appId: '1:497765909762:web:9f2eee64b5f0a0b9f32e1b',
    messagingSenderId: '497765909762',
    projectId: 'flutterpuntoventa',
    authDomain: 'flutterpuntoventa.firebaseapp.com',
    storageBucket: 'flutterpuntoventa.firebasestorage.app',
    measurementId: 'G-PTD4C0YDBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeMDZvjZiTXwzSvbE4N4TGXE-az_NhFtg',
    appId: '1:497765909762:android:ac50efb9b7b1c788f32e1b',
    messagingSenderId: '497765909762',
    projectId: 'flutterpuntoventa',
    storageBucket: 'flutterpuntoventa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwby8V2PKptjQOzrcgckuagST3qI8ScU',
    appId: '1:497765909762:ios:873491287dcdb75cf32e1b',
    messagingSenderId: '497765909762',
    projectId: 'flutterpuntoventa',
    storageBucket: 'flutterpuntoventa.firebasestorage.app',
    iosBundleId: 'com.example.practica1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIwby8V2PKptjQOzrcgckuagST3qI8ScU',
    appId: '1:497765909762:ios:873491287dcdb75cf32e1b',
    messagingSenderId: '497765909762',
    projectId: 'flutterpuntoventa',
    storageBucket: 'flutterpuntoventa.firebasestorage.app',
    iosBundleId: 'com.example.practica1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhc8oPyotczsRX_YQwJjgh0QnXMJDvykE',
    appId: '1:497765909762:web:31c16bf3cd49d1a0f32e1b',
    messagingSenderId: '497765909762',
    projectId: 'flutterpuntoventa',
    authDomain: 'flutterpuntoventa.firebaseapp.com',
    storageBucket: 'flutterpuntoventa.firebasestorage.app',
    measurementId: 'G-2V6MRC88QQ',
  );
}
